---
version: 0.2

environment_variables:
  plaintext:
    HUGO_VERSION: "0.68.3"

phases:
  install:
    commands:
    - echo installing hugo at $HUGO_VERSION
    - curl -Ls https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz -o /tmp/hugo.tar.gz
    - tar -zxf /tmp/hugo.tar.gz -C /tmp
    - mv /tmp/hugo /usr/bin/hugo
  pre_build:
    commands:
    - echo Hugo Config
    - cat blog/tconfig.yaml
    - echo Pulling themes
    - git submodule update --init --recursive
  build:
    commands:
    - hugo -v -s blog/
  post_build:
    commands:
    - echo Deploying to S3
    - hugo deploy -v -s blog/
