baseURL: "https://blog.glasswaves.co/"
languageCode: "en-us"
title: "Glasswaves Co."
theme: "noteworthy"

deployment:
  targets:
    name: "S3 Deployment"
    URL: "s3://glasswaves-co-blog-subdomainbucket86d45e8f-1pjpifrelsfsv"
    cloudFrontDistributionID: "E1AMXLUW18V92A"

params:
  twitter: "https://twitter.com/iamsomewalrus"
  linkedin: "https://www.linkedin.com/in/joseph-feeney/"
  github: "https://github.com/iamatypeofwalrus"
