baseURL: "https://blog.glasswaves.co/"
languageCode: "en-us"
title: "Blog for Glasswaves Co."
theme: "smol"

deployment:
  targets:
    name: "S3 Deployment"
    URL: "s3://glasswaves-co-blog-subdomainbucket86d45e8f-1pjpifrelsfsv"
    cloudFrontDistributionID: "E1AMXLUW18V92A"

staticDir:
- content/posts/assets
- static/

params:
  subtitle: "complexity from simplicity"

menu:
  main:
    - identifier: "posts"
      name: "Posts"
      url: "/posts/"
      weight: 1 
    - identifier: "tags"
      name: "Tags"
      url: "/tags/"
      weight: 3
    - identifier: "about"
      name: "About"
      url: "https://glasswaves.co"
      weight: 4
